package ctos

const (
	CTOS_RESPONSE      = 0x1
	CTOS_UPDATE_DECK   = 0x2
	CTOS_HAND_RESULT   = 0x3
	CTOS_TP_RESULT     = 0x4
	CTOS_PLAYER_INFO   = 0x10
	CTOS_CREATE_GAME   = 0x11
	CTOS_JOIN_GAME     = 0x12
	CTOS_LEAVE_GAME    = 0x13
	CTOS_SURRENDER     = 0x14
	CTOS_TIME_CONFIRM  = 0x15
	CTOS_CHAT          = 0x16
	CTOS_HS_TODUELIST  = 0x20
	CTOS_HS_TOOBSERVER = 0x21
	CTOS_HS_READY      = 0x22
	CTOS_HS_NOTREADY   = 0x23
	CTOS_HS_KICK       = 0x24
	CTOS_HS_START      = 0x25
)
